import React, { act } from "react";
import { createRoot } from "react-dom/client";
import { PrepContainers, validContainerState, validContainerAck } from "./PrepContainers";
import * as api from "../lib/api";
jest.mock("../lib/api",()=>({prepContainers:jest.fn(),previewPrepContainer:jest.fn(),savePrepContainer:jest.fn()}));
const id=n=>`00000000-0000-4000-8000-${String(n).padStart(12,"0")}`;
const stamp={performed_at:"2026-10-05T13:00:00-04:00",business_date:"2026-10-05",timezone_name:"America/New_York",calendar_date_confirmed:true,note:"Measured service transfer"};
const fill={id:id(1),command_id:id(8),store_id:"berts",profile_id:id(2),source_batch_id:id(3),product_id:id(4),base_unit:"lb",factor:"2",quantity:"5",base_quantity:"10",label:"Measured pan A",...stamp};
const emptyState={fill,moves:[],storage:"10",service:"0",allocated:"10",revision:0,voided:false};
const setup={store_id:"berts",definitions:[{id:id(5),name:"Measured pan",current:true,revision:1}],profiles:[{id:id(2),current:true,definition_id:id(5),product_id:id(4),source_unit:"bag",usable_quantity:"5",reviewNeeded:false}],products:[{id:id(6),product_id:id(4),name:"Sauce"}],units:[],lots:[],fills:[emptyState]};
function preview(b){const {action,...fields}=b;let facts=fields,sources={};if(action==="definition")facts={...fields,root_id:null,revision:1};else if(action==="send"){facts={...fields,action,revision:1,storage_delta:"-6",service_delta:"6"};delete facts.calendar_date_confirmed;sources={before:emptyState,after:{storage:"4",service:"6"}};}return {reviewHash:"a".repeat(64),review:{store_id:"berts",action,body:b,table:action==="definition"?"container_definitions":"container_moves",facts,sources,accountingEffect:"none",consumptionEffect:"none"}};}
function ack(p,key){const review=p.review,result={...review.facts,id:id(9),command_id:id(10),store_id:"berts"};if(result.root_id===null)result.root_id=result.id;const command={id:id(10),result_id:result.id,store_id:"berts",action:review.action,request_key:key,review_snapshot:review,review_hash:p.reviewHash};return {command,result,current:review.action==="send"?{...emptyState,moves:[result],revision:1,storage:"4",service:"6"}:null,replayed:false};}
let root,container,number;
beforeEach(()=>{global.IS_REACT_ACT_ENVIRONMENT=true;number=20;Object.defineProperty(global,"crypto",{configurable:true,value:{randomUUID:()=>id(number++)}});jest.clearAllMocks();api.prepContainers.mockResolvedValue(setup);api.previewPrepContainer.mockImplementation((rid,b)=>Promise.resolve(preview(b)));api.savePrepContainer.mockImplementation((rid,b,key)=>Promise.resolve(ack(preview(b.body),key)));container=document.createElement("div");document.body.appendChild(container);root=createRoot(container);});
afterEach(async()=>{await act(async()=>root.unmount());container.remove();});
const render=props=>act(async()=>root.render(<PrepContainers rid="berts" {...props}/>));
const button=text=>[...container.querySelectorAll("button")].find(b=>b.textContent===text);
const click=el=>act(async()=>el.click());
async function input(label,value){const el=container.querySelector(`[aria-label="${label}"]`);await act(async()=>{Object.getOwnPropertyDescriptor(el.tagName==="SELECT"?HTMLSelectElement.prototype:HTMLInputElement.prototype,"value").set.call(el,value);el.dispatchEvent(new Event(el.tagName==="SELECT"?"change":"input",{bubbles:true}));});}
async function definition(){await input("Container name","Measured pan");await input("Stated capacity (optional)","8");await input("Capacity evidence","Reference capacity; actual fill measured separately");await click(button("Review container command"));await click(container.querySelector('[aria-label="Confirm container review"]'));}
async function sending(){await input("Container action","send");await input("Filled container",fill.id);await input("Movement quantity in original measured unit","3");await input("Physical timestamp with offset",stamp.performed_at);await input("Location calendar date",stamp.business_date);await input("Measurement or correction evidence",stamp.note);await click(container.querySelector('[aria-label="Confirm measured contents and calendar day"]'));await click(button("Review container command"));await click(container.querySelector('[aria-label="Confirm container review"]'));}

test("exact decimal state retains tiny values and balanced partial storage/service movement",()=>{const state={...emptyState,fill:{...fill,quantity:"0.000000000001",factor:"0.000000000001",base_quantity:"0.000000000000000000000001"},storage:"0.000000000000000000000001",allocated:"0.000000000000000000000001"};expect(validContainerState(state,"berts")).toBe(true);expect(validContainerState({...state,storage:"0"},"berts")).toBe(false);expect(validContainerState(emptyState,"rudds")).toBe(false);});
test("malformed and overdrawn container history is rejected",()=>{const p=preview({...stamp,action:"send",fill_id:fill.id,quantity:"3",target_move_id:null});const a=ack(p,id(20));expect(validContainerState(a.current,"berts")).toBe(true);for(const change of [{storage:"10"},{allocated:"4"},{revision:0},{moves:[{...a.result,service_delta:"0"}]},{moves:[{...a.result,action:"invented"}]}])expect(validContainerState({...a.current,...change},"berts")).toBe(false);});
test("ack binds request key, result fields, original reviewed snapshot and current immutable history",()=>{const p=preview({...stamp,action:"send",fill_id:fill.id,quantity:"3",target_move_id:null}),pending={key:id(20),body:{expected_review_hash:p.reviewHash},review:p},a=ack(p,pending.key);expect(validContainerAck(a,pending,"berts")).toBe(true);expect(validContainerAck({...a,result:{...a.result,quantity:"4"}},pending,"berts")).toBe(false);expect(validContainerAck({...a,command:{...a.command,request_key:id(21)}},pending,"berts")).toBe(false);expect(validContainerAck({...a,current:{...a.current,moves:[]}},pending,"berts")).toBe(false);});
test("stated capacity is separate from unknown usable capacity and save requires review",async()=>{await render();await input("Container name","Measured pan");await input("Capacity evidence","Reference only");await click(button("Review container command"));expect(button("Save reviewed container command").disabled).toBe(true);expect(container.textContent).toContain("usable unknown");await click(container.querySelector('[aria-label="Confirm container review"]'));await click(button("Save reviewed container command"));expect(api.savePrepContainer).toHaveBeenCalledTimes(1);expect(container.textContent).toContain("Container command saved");});
test("blank and zero movement are held instead of inventing contents",async()=>{await render();await input("Container action","send");await input("Filled container",fill.id);await click(container.querySelector('[aria-label="Confirm measured contents and calendar day"]'));for(const value of ["","0","-1","1e3","NaN"]){await input("Movement quantity in original measured unit",value);await click(container.querySelector('[aria-label="Confirm measured contents and calendar day"]'));await click(button("Review container command"));}expect(api.previewPrepContainer).not.toHaveBeenCalled();});
test("partial send reviews both compartments without accounting consumption",async()=>{await render();await sending();expect(container.textContent).toContain("4 storage / 6 service");await click(button("Save reviewed container command"));expect(api.savePrepContainer.mock.calls[0][1].body.quantity).toBe("3");expect(container.textContent).toContain("do not count as consumption");});
test("lost acknowledgement retains exact command through remount",async()=>{const drafts=new Map();api.savePrepContainer.mockRejectedValueOnce(new Error("Connection lost"));await render({drafts});await definition();await click(button("Save reviewed container command"));const first=api.savePrepContainer.mock.calls[0];await act(async()=>root.render(null));await render({drafts});expect(button("Retry same container command")).toBeTruthy();await click(button("Retry same container command"));expect(api.savePrepContainer.mock.calls[1]).toEqual(first);expect(drafts.has("prep-containers:berts")).toBe(false);});
test("wrong result acknowledgement keeps retry and measurements",async()=>{api.savePrepContainer.mockImplementationOnce((rid,b,key)=>Promise.resolve({...ack(preview(b.body),key),result:{...ack(preview(b.body),key).result,name:"Wrong pan"}}));await render();await definition();await click(button("Save reviewed container command"));expect(container.textContent).toContain("did not match");expect(button("Retry same container command")).toBeTruthy();await click(button("Retry same container command"));expect(api.savePrepContainer.mock.calls[1]).toEqual(api.savePrepContainer.mock.calls[0]);});
test("stale rejection requires explicit revise and a new preview",async()=>{api.savePrepContainer.mockRejectedValueOnce({response:{status:409,data:{detail:"Source changed"}}});await render();await definition();await click(button("Save reviewed container command"));expect(button("Revise rejected container command")).toBeTruthy();await click(button("Revise rejected container command"));expect(button("Save reviewed container command")).toBeFalsy();expect(container.querySelector('[aria-label="Container name"]').value).toBe("Measured pan");});
test("wrong location and altered measurement preview never becomes savable",async()=>{await render();await input("Container name","Measured pan");await input("Capacity evidence","Measured reference");api.previewPrepContainer.mockImplementationOnce((rid,b)=>Promise.resolve({...preview(b),review:{...preview(b).review,store_id:"rudds"}}));await click(button("Review container command"));expect(button("Save reviewed container command")).toBeFalsy();api.previewPrepContainer.mockImplementationOnce((rid,b)=>Promise.resolve({...preview(b),review:{...preview(b).review,body:{...b,name:"Altered"}}}));await click(button("Review container command"));expect(button("Save reviewed container command")).toBeFalsy();});
test("location navigation ignores late saves while preserving pending origin request",async()=>{const drafts=new Map();let resolve;api.savePrepContainer.mockImplementationOnce(()=>new Promise(r=>{resolve=r;}));await render({drafts});await definition();await click(button("Save reviewed container command"));const first=api.savePrepContainer.mock.calls[0];await render({rid:"rudds",drafts});await act(async()=>resolve(ack(preview(first[1].body),first[2])));expect(drafts.get("prep-containers:berts").pending.key).toBe(first[2]);expect(container.textContent).not.toContain("Container command saved");});
test("cleared session drafts cannot be resurrected by a late save",async()=>{const drafts=new Map();let reject;api.savePrepContainer.mockImplementationOnce(()=>new Promise((r,j)=>{reject=j;}));await render({drafts});await definition();await click(button("Save reviewed container command"));drafts.clear();await act(async()=>reject({response:{status:409,data:{detail:"Changed"}}}));expect(drafts.size).toBe(0);});
test("bad container readback is held and failed reads do not fabricate an empty inventory",async()=>{api.prepContainers.mockResolvedValueOnce({...setup,fills:[{...emptyState,storage:"0"}]});await render();expect(container.textContent).toContain("readback is incomplete");expect(container.querySelector('[aria-label="Container action"]')).toBeFalsy();api.prepContainers.mockRejectedValueOnce(new Error("Offline"));await click(button("Refresh containers"));expect(container.textContent).toContain("Offline");});
test("combined lot quantities cannot hide container reservations or change pinned acknowledgement identity",async()=>{api.prepContainers.mockResolvedValueOnce({...setup,lots:[{id:id(3),remainingRecordedQuantity:"38",containerStorage:"10",containerService:"0",totalRemainingRecordedQuantity:"38"}]});await render();expect(container.textContent).toContain("readback is incomplete");const p=preview({...stamp,action:"send",fill_id:fill.id,quantity:"3",target_move_id:null}),pending={key:id(20),body:{expected_review_hash:p.reviewHash},review:p},a=ack(p,pending.key);expect(validContainerAck({...a,current:{...a.current,fill:{...fill,base_unit:"gal"}}},pending,"berts")).toBe(false);});
