import React,{act} from 'react';
import {createRoot} from 'react-dom/client';
import {PrepPeriodJournal} from './PrepPeriodJournal';
import * as api from '../lib/api';
jest.mock('../lib/api');
let root,container;
const counts=[{id:'a',performed_at:'09:00',revision:1,scope:['p']},{id:'b',performed_at:'13:00',revision:1,scope:['p','q'],definitions:[{product:{product_id:'q',name:'New sauce'}}]}];
const report={opening:counts[0],closing:counts[1],prepared:[{product_id:'p',name:'Protein',base_unit:'lb',openingQuantity:'20.000000000001',recordedProduction:'48',closingQuantity:'25',observedDepletion:'43.000000000001',recordedNestedUseMeasured:'20',recordedNestedUseEstimated:'0',recordedWaste:'5',serviceUseOrUnrecordedLoss:'18.000000000001',flags:[]}],rawExplanations:[],scopeHandoff:{zeroAdditions:[{product_id:'q',base_quantity:'0',base_unit:'lb',evidence:'Empty at opening'}]}};
const data={store_id:'berts',closures:[],reopenings:[]};
const button=t=>[...container.querySelectorAll('button')].find(b=>b.textContent===t);
const click=async el=>act(async()=>el.click());
const input=async(label,value)=>act(async()=>{const el=container.querySelector(`[aria-label="${label}"]`);Object.getOwnPropertyDescriptor(el.tagName==='SELECT'?HTMLSelectElement.prototype:HTMLInputElement.prototype,'value').set.call(el,value);el.dispatchEvent(new Event(el.tagName==='SELECT'?'change':'input',{bubbles:true}));});
async function render(){await act(async()=>root.render(<PrepPeriodJournal restaurantId="berts"/>));}
async function enter(){await render();await input('opening saved-period count','a');await input('closing saved-period count','b');await input('opening saved-period cutoff','after_all');await input('closing saved-period cutoff','before_all');await click(container.querySelector('[aria-label="Confirm saved period cutoffs"]'));await click(container.querySelector('[aria-label="Confirm added zero q"]'));await input('Added zero evidence q','Empty at opening');await input('Analytical period review reason','Reviewed partial period');}
async function approve(){await click(button('Review analytical period action'));await click(container.querySelector('[aria-label="Approve analytical period action"]'));}
beforeEach(()=>{jest.clearAllMocks();global.IS_REACT_ACT_ENVIRONMENT=true;Object.defineProperty(global,'crypto',{configurable:true,value:{randomUUID:jest.fn(()=>'period-key')}});
  api.nativePrepPeriodJournal.mockResolvedValue(data);api.nativePrepPeriodCounts.mockResolvedValue({store_id:'berts',counts});
  api.previewNativePrepPeriodClose.mockResolvedValue({reviewHash:'hash',review:{store_id:'berts',report}});
  api.saveNativePrepPeriodClose.mockResolvedValue({event:{id:'saved',store_id:'berts',review_hash:'hash',closing_count_id:'b'}});
  container=document.createElement('div');document.body.appendChild(container);root=createRoot(container);});
afterEach(async()=>{await act(async()=>root.unmount());container.remove();});
test('explicit cutoffs and measured added zeros are required before review',async()=>{await render();await click(button('Review analytical period action'));expect(api.previewNativePrepPeriodClose).not.toHaveBeenCalled();await enter();await click(container.querySelector('[aria-label="Confirm added zero q"]'));await click(button('Review analytical period action'));expect(api.previewNativePrepPeriodClose).not.toHaveBeenCalled();});
test('review retains precision and requires separate approval before saving',async()=>{await enter();await click(button('Review analytical period action'));expect(container.textContent).toContain('20.000000000001');expect(container.textContent).toContain('Coverage remains partial');expect(container.textContent).toContain('Food Cost is unchanged');expect(button('Save reviewed analytical period action').disabled).toBe(true);await click(container.querySelector('[aria-label="Approve analytical period action"]'));await click(button('Save reviewed analytical period action'));expect(api.saveNativePrepPeriodClose.mock.calls[0][1].submission.zero_additions).toEqual([{product_id:'q',zero_at_opening_confirmed:true,evidence:'Empty at opening'}]);expect(container.textContent).toContain('Analytical snapshot saved');});
test('editing boundary or evidence invalidates approval and zero confirmation',async()=>{await enter();await approve();await input('Added zero evidence q','Different evidence');expect(container.querySelector('[aria-label="Analytical period action review"]')).toBeNull();await approve();await input('closing saved-period cutoff','after_all');expect(container.querySelector('[aria-label="Confirm saved period cutoffs"]').checked).toBe(false);expect(container.querySelector('[aria-label="Confirm added zero q"]').checked).toBe(false);});
test('uncertain acknowledgment freezes controls and retries identical body and key',async()=>{api.saveNativePrepPeriodClose.mockRejectedValueOnce(new Error('Uncertain acknowledgment'));await enter();await approve();await click(button('Save reviewed analytical period action'));expect(container.querySelector('[aria-label="Saved period action"]').closest('fieldset').disabled).toBe(true);expect(button('Refresh saved prep periods').disabled).toBe(true);await click(button('Retry same analytical period action'));expect(api.saveNativePrepPeriodClose.mock.calls[0]).toEqual(api.saveNativePrepPeriodClose.mock.calls[1]);});
test('foreign acknowledgment and definite stale conflict cannot display success',async()=>{api.saveNativePrepPeriodClose.mockResolvedValueOnce({event:{id:'saved',store_id:'rudds',review_hash:'hash'}});await enter();await approve();await click(button('Save reviewed analytical period action'));expect(container.textContent).toContain('not confirmed');api.saveNativePrepPeriodClose.mockRejectedValueOnce({response:{status:409,data:{detail:'Period sources changed'}}});await click(button('Retry same analytical period action'));expect(container.querySelector('[aria-label="Analytical period action review"]')).toBeNull();expect(button('Refresh saved prep periods').disabled).toBe(false);});
test('reopening lists full suffix and preserves saved historical quantities',async()=>{const closure={id:'saved',ordinal:1,reason:'Original partial review',recorded_by:'Manager',recorded_at:'Today',freshness:{status:'stale',reason:'Backfill changed'},review_snapshot:{report}};api.nativePrepPeriodJournal.mockResolvedValue({...data,closures:[closure]});api.previewNativePrepPeriodReopen.mockResolvedValue({reviewHash:'reopen-hash',review:{store_id:'berts',snapshots:[{id:'saved',freshness:{status:'stale',reason:'Backfill changed'}},{id:'later',freshness:{status:'current'}}]}});api.saveNativePrepPeriodReopen.mockResolvedValue({event:{id:'reopen',store_id:'berts',review_hash:'reopen-hash',closure_ids:['saved','later']}});await render();expect(container.textContent).toContain('20.000000000001');expect(container.textContent).toContain('stale');await input('Saved period action','reopen');await input('Earliest affected saved period','saved');await input('Analytical period review reason','Resolve backfill');await approve();expect(container.querySelector('[aria-label="Analytical period action review"]').textContent).toContain('later');await click(button('Save reviewed analytical period action'));expect(api.saveNativePrepPeriodReopen).toHaveBeenCalledWith('berts',{submission:{from_closure_id:'saved',reason:'Resolve backfill'},expected_review_hash:'reopen-hash',reviewed:true},'period-key');});
test('failed refresh and wrong-location setup remain visible failures',async()=>{api.nativePrepPeriodCounts.mockRejectedValueOnce(new Error('Counts unavailable'));await render();expect(container.textContent).toContain('Counts unavailable');api.nativePrepPeriodJournal.mockResolvedValue({...data,store_id:'rudds'});await click(button('Refresh saved prep periods'));expect(container.textContent).toContain('location was not confirmed');});
