import React,{act} from "react";
import {createRoot} from "react-dom/client";
import {StaffProductionSubmission,StaffProductionDecisions,validProductionAck,validProductionReview,productionSame} from "./StaffPrepProduction";
import * as api from "../lib/api";
jest.mock("../lib/api",()=>({staffProductionSetup:jest.fn(),previewStaffProduction:jest.fn(),submitStaffProduction:jest.fn(),staffProductionReviewSetup:jest.fn(),previewStaffProductionDecision:jest.fn(),decideStaffProduction:jest.fn()}));
const id=n=>`00000000-0000-4000-8000-${String(n).padStart(12,"0")}`,hash="a".repeat(64),day="2026-10-08",track="daily";
const member={id:id(2),store_id:"berts",name:"Cook A",role:"cook",active:true};
const progress={task_id:id(1),status:"open",reviewed_base_quantity:"0",closed:false,needs_review:false,links:[]};
const task={id:id(1),store_id:"berts",included:true,planned_quantity:"4",recipe_version_id:id(4),product_id:id(5),version_id:id(6),task_snapshot:{name:"Sauce",source_unit:"bag"}};
const assigned={id:id(3),store_id:"berts",task_id:task.id,staff_member_id:member.id};
const plan={tasks:[{...task,name:"Sauce",quantity:"4",source_unit:"bag",assignment:assigned.id,assigned_member:member,roster_changed:false,progress}]};
const line={id:id(7),source_unit:"lb",factor:"1",source_kind:"raw",raw_item_code:"RAW"};
const recipe={id:id(4),lines:[line],outputUnit:"bag",reviewNeeded:false};
const batch={recipe_version_id:recipe.id,planned_batches:"1",output_quantity:"2",performed_at:"2026-10-08T10:00:00-04:00",business_date:day,timezone_name:"America/New_York",calendar_date_confirmed:true,single_output_confirmed:true,note:"Measured output",inputs:[{recipe_line_id:line.id,quantity:"3",source_unit:"lb",factor:"1",measurement_basis:"measured",source_batch_id:null,included_loss_quantity:null,loss_evidence:null,evidence:"Scale"}]};
function batchReview(b){return {reviewHash:hash,review:{kind:"initial",revision:1,root_id:null,predecessor_id:null,recipe_version_id:b.recipe_version_id,business_date:b.business_date,timezone_name:b.timezone_name,base_unit:"lb",product_id:task.product_id,usableBaseOutput:b.output_quantity,outputUnit:"bag",batch:b,
  inputs:b.inputs.map(x=>({...x,base_quantity:x.quantity})),movements:[...b.inputs.map(x=>({side:"apply",kind:"raw_input",recipe_line_id:x.recipe_line_id,source_batch_id:x.source_batch_id,quantity:`-${x.quantity}`,reverses_movement_id:null})),{side:"apply",kind:"output",quantity:b.output_quantity,reverses_movement_id:null}]}};}
function review(body){const b=body.submission;return {reviewHash:hash,review:{store_id:"berts",day,track,submission:b,predecessor_id:b.expected_revision?id(10):null,submitted_by:"shared-pin",credential_kind:"shared_pin",identity_verified:false,sources:{task,assignment:assigned,member,progress},batch:b.batch?batchReview(b.batch):null,accountingEffect:"none",productionEffect:"none"}};}
function submitAck(p,key){const b=p.review.submission,s={id:b.expected_revision?id(11):b.root_id,store_id:"berts",root_id:b.root_id,task_id:b.task_id,staff_member_id:b.staff_member_id,assignment_id:b.assignment_id,kind:b.kind,note:b.note,revision:b.expected_revision+1,predecessor_id:p.review.predecessor_id,submitted_by:"shared-pin",credential_kind:"shared_pin",request_key:key,request_fingerprint:hash,review_hash:p.reviewHash,review_snapshot:p.review};return {submission:s,history:{root_id:b.root_id,events:[s],decisions:[]},productionEffect:"none"};}
const initialBody={submission:{root_id:id(10),expected_revision:0,task_id:task.id,staff_member_id:member.id,assignment_id:assigned.id,kind:"submit",batch,note:"Measured"}};
const stored=submitAck(review(initialBody),id(20)).submission;
const state=(staff=false)=>({store_id:"berts",day,track,selected_member_id:staff?member.id:null,accountingEffect:"none",submissions:staff?[]:[{root_id:stored.root_id,events:[stored],decisions:[]}],...(staff?{identity_verified:false,setup:{recipes:[recipe],lots:[],policy:{timezone_name:"America/New_York"}}}: {})});
function decisionReview(body){const p=batchReview(batch);p.review.staff_submission_id=stored.id;return {reviewHash:hash,review:{store_id:"berts",day,track,decision:body,submission:stored,sources:body.decision==="accepted"?{task,assignment:assigned,progress,execution_revision:1}:null,batch:body.decision==="accepted"?p:null,accountingEffect:"none",productionEffect:body.decision==="accepted"?"record_once":"none"}};}
function decisionAck(p,key){const d=p.review.decision,accepted=d.decision==="accepted",b=accepted?{id:id(30),store_id:"berts",kind:"initial",source_kind:"production",root_id:id(30),predecessor_id:null,recipe_version_id:recipe.id,business_date:day,request_key:key,request_fingerprint:hash,recorded_by:"owner",review_hash:hash,review_snapshot:p.review.batch.review}:null;
  const e=accepted?{id:id(31),store_id:"berts",action:"link",task_id:task.id,batch_event_id:b.id,batch_root_id:b.id,actor:"owner",reason:d.note,request_key:key,request_fingerprint:hash,revision:2,review_snapshot:{staff_submission_id:stored.id,batch:b,progress_before:progress}}:null;
  const f=accepted&&d.task_complete?{id:id(32),store_id:"berts",action:"finish",task_id:task.id,predecessor_id:e.id,revision:3,actor:"owner",reason:d.note,request_fingerprint:hash,review_snapshot:{staff_submission_id:stored.id}}:null;
  const saved={id:id(33),store_id:"berts",submission_id:stored.id,decision:d.decision,task_complete:d.task_complete,note:d.note,recorded_by:"owner",request_key:key,request_fingerprint:hash,review_hash:p.reviewHash,review_snapshot:p.review,batch_event_id:b?.id||null,execution_event_id:e?.id||null,finish_event_id:f?.id||null};
  return {decision:saved,batch_event:b,execution_event:e,finish_event:f,history:{root_id:stored.root_id,events:[stored],decisions:[saved]},current:{store_id:"berts",day,track,members:[member],assignments:[{task_id:task.id,current:null,history:[],current_member:null,roster_changed:false}],execution:{store_id:"berts",prep_date:day,track,status:"released",revision:3,tasks:[task],task_progress:[progress]}}};}
let root,container,n;
beforeEach(()=>{global.IS_REACT_ACT_ENVIRONMENT=true;n=100;Object.defineProperty(global,"crypto",{configurable:true,value:{randomUUID:()=>id(n++)}});jest.clearAllMocks();api.staffProductionSetup.mockResolvedValue(state(true));api.staffProductionReviewSetup.mockResolvedValue(state());api.previewStaffProduction.mockImplementation((r,d,t,b)=>Promise.resolve(review(b)));api.submitStaffProduction.mockImplementation((r,d,t,b,k)=>Promise.resolve(submitAck(review(b),k)));api.previewStaffProductionDecision.mockImplementation((r,d,t,b)=>Promise.resolve(decisionReview(b)));api.decideStaffProduction.mockImplementation((r,d,t,b,k)=>{const {reviewed,expected_review_hash,...decision}=b;return Promise.resolve(decisionAck(decisionReview(decision),k));});container=document.createElement("div");document.body.appendChild(container);root=createRoot(container);});
afterEach(async()=>{await act(async()=>root.unmount());container.remove();});
const render=(props={})=>act(async()=>root.render(<StaffProductionSubmission rid="berts" day={day} track={track} staffId={member.id} pin="4826" plan={plan} {...props}/>));
const renderManager=(props={})=>act(async()=>root.render(<StaffProductionDecisions rid="berts" day={day} track={track} {...props}/>));
const button=t=>[...container.querySelectorAll("button")].find(b=>b.textContent===t);
const click=e=>act(async()=>e.click());
async function input(label,value){const e=container.querySelector(`[aria-label="${label}"]`);await act(async()=>{Object.getOwnPropertyDescriptor(e.tagName==="SELECT"?HTMLSelectElement.prototype:HTMLInputElement.prototype,"value").set.call(e,value);e.dispatchEvent(new Event(e.tagName==="SELECT"?"change":"input",{bubbles:true}));});}
async function fill(){await input("Assigned production task",task.id);for(const [k,v] of Object.entries({"Recipe batches prepared":"1","Measured usable production":"2","Production time with offset":batch.performed_at,"Production measurement evidence":"Measured output","Gross ingredient 1":"3","Ingredient basis 1":"measured","Ingredient evidence 1":"Scale","Production review reason":"Measured"}))await input(k,v);await click(container.querySelector('[aria-label="Confirm production calendar date"]'));await click(container.querySelector('[aria-label="Confirm single usable output"]'));await click(button("Review production record"));await click(container.querySelector('[aria-label="Confirm production review"]'));}
async function managerReview(){await input("Pending production submission",stored.id);await input("Production review reason","Manager inspected");await click(button("Review production record"));await click(container.querySelector('[aria-label="Confirm production review"]'));}

test("exact decimal comparisons preserve small quantities without float rounding",()=>{expect(productionSame("0.000000000001","1E-12","quantity")).toBe(true);expect(productionSame("2.000000000001","2.000000000002","quantity")).toBe(false);});
test("submission review pins task, identity, gross inputs, output and physical date",()=>{const p=review(initialBody);expect(validProductionReview(p,initialBody,"berts",day,track)).toBe(true);for(const change of [{day:"2026-10-09"},{identity_verified:true},{productionEffect:"record_once"}])expect(validProductionReview({...p,review:{...p.review,...change}},initialBody,"berts",day,track)).toBe(false);const forged=JSON.parse(JSON.stringify(p));forged.review.batch.review.inputs[0].base_quantity="999";expect(validProductionReview(forged,initialBody,"berts",day,track)).toBe(false);});
test("staff acknowledgement confirms retained body and immutable original revision",()=>{const p=review(initialBody),pending={review:p,key:id(20),body:{expected_review_hash:p.reviewHash}},a=submitAck(p,pending.key);expect(validProductionAck(a,pending,"berts",day,track)).toBe(true);for(const change of [{task_id:id(99)},{staff_member_id:id(98)},{assignment_id:id(97)},{request_key:id(96)},{kind:"withdraw"}])expect(validProductionAck({...a,submission:{...a.submission,...change}},pending,"berts",day,track)).toBe(false);});
test("manager acknowledgement requires matching batch link and explicit optional finish",()=>{for(const complete of [false,true]){const p=decisionReview({submission_id:stored.id,decision:"accepted",task_complete:complete,note:"Checked"}),pending={review:p,key:id(20),body:{expected_review_hash:p.reviewHash}},a=decisionAck(p,pending.key);expect(validProductionAck(a,pending,"berts",day,track,true)).toBe(true);expect(validProductionAck({...a,batch_event:null},pending,"berts",day,track,true)).toBe(false);expect(validProductionAck({...a,execution_event:{...a.execution_event,batch_event_id:id(99)}},pending,"berts",day,track,true)).toBe(false);if(complete)expect(validProductionAck({...a,finish_event:null},pending,"berts",day,track,true)).toBe(false);}});
test("rejection acknowledgement cannot contain a production event",()=>{const p=decisionReview({submission_id:stored.id,decision:"rejected",task_complete:false,note:"Wrong measurement"}),pending={review:p,key:id(20),body:{expected_review_hash:p.reviewHash}},a=decisionAck(p,pending.key);expect(validProductionAck(a,pending,"berts",day,track,true)).toBe(true);expect(validProductionAck({...a,batch_event:{id:id(99)}},pending,"berts",day,track,true)).toBe(false);});
test("staff form preserves measurements and creates no success before review and acknowledgement",async()=>{await render();await fill();await click(button("Save reviewed production record"));expect(container.textContent).toContain("Submission saved for manager review; no production recorded");expect(api.submitStaffProduction.mock.calls[0][2]).toBe(track);expect(api.submitStaffProduction.mock.calls[0][5]).toBe("4826");expect(api.submitStaffProduction.mock.calls[0][3]).not.toHaveProperty("pin");});
test("lost response retains exact staff request across remount without storing PIN",async()=>{const drafts=new Map();api.submitStaffProduction.mockRejectedValueOnce(new Error("Lost response"));await render({drafts});await fill();await click(button("Save reviewed production record"));const first=api.submitStaffProduction.mock.calls[0];expect(JSON.stringify([...drafts.values()])).not.toContain("4826");await act(async()=>root.render(null));await render({drafts});await click(button("Retry same production record"));expect(api.submitStaffProduction.mock.calls[1]).toEqual(first);expect(drafts.size).toBe(0);});
test("missing batch acknowledgement holds manager success and original request",async()=>{api.decideStaffProduction.mockImplementationOnce((r,d,t,b,k)=>{const {expected_review_hash,reviewed,...decision}=b;return Promise.resolve({...decisionAck(decisionReview(decision),k),batch_event:null});});await renderManager();await managerReview();await click(button("Save reviewed production record"));expect(container.textContent).toContain("not confirmed");expect(button("Retry same production record")).toBeTruthy();expect(container.querySelector('[role="status"]')).toBeNull();});
test("manager partial acceptance remains open unless finish is explicitly checked",async()=>{await renderManager();await managerReview();expect(container.textContent).toContain("Accept this partial batch; task remains open");await click(button("Save reviewed production record"));expect(api.decideStaffProduction.mock.calls[0][3].task_complete).toBe(false);expect(container.textContent).toContain("accepted and linked once");});
test("stale decision retains reason until explicit revision and fresh review",async()=>{api.decideStaffProduction.mockRejectedValueOnce({response:{status:409,data:{detail:"Assignment changed"}}});await renderManager();await managerReview();await click(button("Save reviewed production record"));expect(button("Retry same production record")).toBeTruthy();await click(button("Revise rejected production record"));expect(container.querySelector('[aria-label="Production review reason"]').value).toBe("Manager inspected");expect(button("Save reviewed production record")).toBeFalsy();});
test("late submission callback cannot mutate another selected date",async()=>{let resolve;const drafts=new Map();api.submitStaffProduction.mockImplementationOnce(()=>new Promise(r=>{resolve=r;}));await render({drafts});await fill();await click(button("Save reviewed production record"));const call=api.submitStaffProduction.mock.calls[0];await render({day:"2026-10-09",drafts});await act(async()=>resolve(submitAck(review(call[3]),call[4])));expect(container.querySelector('[role="status"]')).toBeNull();expect([...drafts.values()][0].pending.key).toBe(call[4]);});
test("cleared logout scope cannot be recreated by a late rejection",async()=>{let reject;const drafts=new Map();api.submitStaffProduction.mockImplementationOnce(()=>new Promise((r,j)=>{reject=j;}));await render({drafts});await fill();await click(button("Save reviewed production record"));drafts.clear();await act(async()=>reject({response:{status:409,data:{detail:"Changed"}}}));expect(drafts.size).toBe(0);});
test("wrong-scope read is held instead of becoming an empty task history",async()=>{api.staffProductionSetup.mockResolvedValueOnce({...state(true),store_id:"rudds"});await render();expect(container.textContent).toContain("not confirmed");expect(container.querySelector('[aria-label="Assigned production task"]')).toBeNull();});
