import React,{act} from "react";
import {createRoot} from "react-dom/client";
import {StaffPrepAssignments,StaffPrepTaskPlan,validAssignmentAck,validAssignmentState} from "./StaffPrepTasks";
import {StaffSheet} from "./StaffSheet";
import * as api from "../lib/api";
jest.mock("../lib/api",()=>({staffPrepTaskSetup:jest.fn(),previewStaffPrepAssignment:jest.fn(),saveStaffPrepAssignment:jest.fn(),staffPrepTaskPlan:jest.fn(),staffPrepTasksEnabled:true,verifyStaffPin:jest.fn(),staffTaskInbox:jest.fn(),identifyStaffMember:jest.fn(),staffPrepsheet:jest.fn()}));
jest.mock("../lib/push",()=>({pushSupported:()=>false}));
const id=n=>`00000000-0000-4000-8000-${String(n).padStart(12,"0")}`;
const day="2026-10-08",track="daily",member={id:id(2),store_id:"berts",name:"Cook A",role:"cook",active:true};
const task={id:id(1),store_id:"berts",included:true,planned_quantity:"4",task_snapshot:{name:"Sauce",source_unit:"bag"}};
const progress={task_id:task.id,status:"open",reviewed_base_quantity:"0",closed:false,needs_review:false};
const setup={store_id:"berts",day,track,members:[member],assignments:[{task_id:task.id,current:null,history:[],current_member:null,roster_changed:false}],execution:{store_id:"berts",prep_date:day,track,status:"released",revision:1,tasks:[task],task_progress:[progress]}};
function plan(b){return {reviewHash:"a".repeat(64),review:{store_id:"berts",day,track,assignment:b,task,progress,member:b.staff_member_id?member:null,predecessor_id:null,accountingEffect:"none",productionEffect:"none"}};}
function ack(p,key){const r=p.review,b=r.assignment,a={id:id(3),store_id:"berts",task_id:b.task_id,staff_member_id:b.staff_member_id,note:b.note,revision:b.expected_revision+1,predecessor_id:r.predecessor_id,request_key:key,review_hash:p.reviewHash,review_snapshot:r};return {assignment:a,assignment_history:[a],current:{...setup,assignments:[{task_id:task.id,current:a,history:[a],current_member:b.staff_member_id?member:null,roster_changed:false}]},replayed:false};}
const staffRead=(d=day,m=null)=>({store_id:"berts",day:d,track,selected_member_id:m,status:"released",identity_verified:false,tasks:[{id:task.id,name:"Sauce",quantity:"4",source_unit:"bag",base_unit:"lb",progress,assigned_member:member,roster_changed:false}]});
let root,container,number;
beforeEach(()=>{global.IS_REACT_ACT_ENVIRONMENT=true;number=20;Object.defineProperty(global,"crypto",{configurable:true,value:{randomUUID:()=>id(number++)}});jest.clearAllMocks();api.staffPrepTaskSetup.mockResolvedValue(setup);api.previewStaffPrepAssignment.mockImplementation((rid,d,t,b)=>Promise.resolve(plan(b)));api.saveStaffPrepAssignment.mockImplementation((rid,d,t,b,key)=>Promise.resolve(ack(plan(b.assignment),key)));api.staffPrepTaskPlan.mockImplementation((rid,b)=>Promise.resolve(staffRead(b.day,b.staff_member_id)));api.verifyStaffPin.mockResolvedValue({ok:true,staff:[{...member,role:"owner_admin"}]});api.staffTaskInbox.mockResolvedValue({tasks:[]});container=document.createElement("div");document.body.appendChild(container);root=createRoot(container);});
afterEach(async()=>{await act(async()=>root.unmount());container.remove();});
const render=(props={})=>act(async()=>root.render(<StaffPrepAssignments rid="berts" day={day} track={track} {...props}/>));
const button=text=>[...container.querySelectorAll("button")].find(b=>b.textContent===text);
const click=el=>act(async()=>el.click());
async function input(label,value){const el=container.querySelector(`[aria-label="${label}"]`);await change(el,value);}
async function change(el,value){await act(async()=>{Object.getOwnPropertyDescriptor(el.tagName==="SELECT"?HTMLSelectElement.prototype:HTMLInputElement.prototype,"value").set.call(el,value);el.dispatchEvent(new Event(el.tagName==="SELECT"?"change":"input",{bubbles:true}));});}
async function assignment(){await input("Prep assignment task",task.id);await input("Assigned staff",member.id);await input("Assignment reason","Reviewed roster assignment");await click(button("Review staff assignment"));await click(container.querySelector('[aria-label="Confirm staff assignment"]'));}
const renderStaff=props=>act(async()=>root.render(<StaffPrepTaskPlan rid="berts" pin="4826" staffId={member.id} track={track} {...props}/>));

test("assignment acknowledgement pins request, task, member, reason and immutable history",()=>{const b={task_id:task.id,staff_member_id:member.id,expected_revision:0,note:"Reviewed"},p=plan(b),pending={key:id(20),body:{expected_review_hash:p.reviewHash},review:p},a=ack(p,pending.key);expect(validAssignmentState(a.current,"berts",day,track)).toBe(true);expect(validAssignmentAck(a,pending,"berts",day,track)).toBe(true);for(const change of [{request_key:id(21)},{staff_member_id:id(22)},{note:"Different"},{task_id:id(23)},{revision:2}])expect(validAssignmentAck({...a,assignment:{...a.assignment,...change}},pending,"berts",day,track)).toBe(false);expect(validAssignmentAck({...a,current:{...a.current,assignments:[]}},pending,"berts",day,track)).toBe(false);});
test("manager save requires preview and explicit review",async()=>{await render();await input("Prep assignment task",task.id);await input("Assigned staff",member.id);await input("Assignment reason","Reviewed");await click(button("Review staff assignment"));expect(button("Save reviewed staff assignment").disabled).toBe(true);await click(container.querySelector('[aria-label="Confirm staff assignment"]'));await click(button("Save reviewed staff assignment"));expect(container.textContent).toContain("Assignment saved and confirmed");expect(api.saveStaffPrepAssignment.mock.calls[0][3].assignment).toEqual({task_id:task.id,staff_member_id:member.id,expected_revision:0,note:"Reviewed"});});
test("exact acknowledgement survives replacement of the original dated draft",()=>{const b={task_id:task.id,staff_member_id:member.id,expected_revision:0,note:"Reviewed"},p=plan(b),pending={key:id(20),body:{expected_review_hash:p.reviewHash},review:p},a=ack(p,pending.key);const newTask={...task,id:id(50)},current={...setup,execution:{...setup.execution,status:"draft",tasks:[newTask]},assignments:[{task_id:newTask.id,current:null,history:[],current_member:null,roster_changed:false}]};expect(validAssignmentAck({...a,current},pending,"berts",day,track)).toBe(true);expect(validAssignmentAck({...a,current,assignment_history:[{...a.assignment,predecessor_id:id(51)}]},pending,"berts",day,track)).toBe(false);});
test("lost acknowledgement retains exact reviewed assignment across remount",async()=>{const drafts=new Map();api.saveStaffPrepAssignment.mockRejectedValueOnce(new Error("Lost response"));await render({drafts});await assignment();await click(button("Save reviewed staff assignment"));const first=api.saveStaffPrepAssignment.mock.calls[0];await act(async()=>root.render(null));await render({drafts});await click(button("Retry same staff assignment"));expect(api.saveStaffPrepAssignment.mock.calls[1]).toEqual(first);expect(drafts.size).toBe(0);});
test("wrong acknowledgement cannot clear draft or announce success",async()=>{api.saveStaffPrepAssignment.mockImplementationOnce((rid,d,t,b,key)=>Promise.resolve({...ack(plan(b.assignment),key),assignment:{...ack(plan(b.assignment),key).assignment,staff_member_id:id(99)}}));await render();await assignment();await click(button("Save reviewed staff assignment"));expect(container.textContent).toContain("not confirmed");expect(button("Retry same staff assignment")).toBeTruthy();expect(container.querySelector('[role="status"]')).toBeNull();});
test("stale assignment remains frozen until explicit revision and fresh review",async()=>{api.saveStaffPrepAssignment.mockRejectedValueOnce({response:{status:409,data:{detail:"Assignment changed"}}});await render();await assignment();await click(button("Save reviewed staff assignment"));expect(button("Retry same staff assignment")).toBeTruthy();await click(button("Revise rejected staff assignment"));expect(container.querySelector('[aria-label="Assignment reason"]').value).toBe("Reviewed roster assignment");expect(button("Save reviewed staff assignment")).toBeFalsy();});
test("wrong date or staff preview cannot be saved",async()=>{await render();await input("Prep assignment task",task.id);await input("Assigned staff",member.id);await input("Assignment reason","Reviewed");api.previewStaffPrepAssignment.mockImplementationOnce((rid,d,t,b)=>Promise.resolve({...plan(b),review:{...plan(b).review,day:"2026-10-09"}}));await click(button("Review staff assignment"));expect(button("Save reviewed staff assignment")).toBeFalsy();});
test("late save cannot mutate another date or restore cleared session",async()=>{const drafts=new Map();let resolve;api.saveStaffPrepAssignment.mockImplementationOnce(()=>new Promise(r=>{resolve=r;}));await render({drafts});await assignment();await click(button("Save reviewed staff assignment"));const first=api.saveStaffPrepAssignment.mock.calls[0];await render({day:"2026-10-09",drafts});await act(async()=>resolve(ack(plan(first[3].assignment),first[4])));expect(container.querySelector('[role="status"]')).toBeNull();expect(drafts.get(`prep-assign:berts:${day}:${track}`).pending.key).toBe(first[4]);});
test("cleared assignment scope cannot be resurrected by late rejection",async()=>{const drafts=new Map();let reject;api.saveStaffPrepAssignment.mockImplementationOnce(()=>new Promise((r,j)=>{reject=j;}));await render({drafts});await assignment();await click(button("Save reviewed staff assignment"));drafts.clear();await act(async()=>reject({response:{status:409,data:{detail:"Changed"}}}));expect(drafts.size).toBe(0);});
test("staff view sends explicit date and optional claimed roster filter with no completion control",async()=>{await renderStaff();expect(api.staffPrepTaskPlan.mock.calls[0][1]).toMatchObject({pin:"4826",track:"daily",staff_member_id:null});await input("Staff prep date",day);await click(container.querySelector('[aria-label="Show my roster assignments"]'));expect(api.staffPrepTaskPlan.mock.calls.at(-1)[1]).toEqual({pin:"4826",day,track,staff_member_id:member.id});expect(container.textContent).toContain("claimed identity");expect(container.textContent).toContain("4 bag planned");expect(container.querySelector('[data-testid="staff-confirm-done-button"]')).toBeNull();});
test("failed or wrong-date read never becomes empty or older released plan",async()=>{api.staffPrepTaskPlan.mockRejectedValueOnce(new Error("Offline"));await renderStaff();expect(container.textContent).toContain("Offline");expect(container.textContent).not.toContain("No released plan");api.staffPrepTaskPlan.mockImplementationOnce((rid,b)=>Promise.resolve(staffRead("1999-01-01")));await click(button("Refresh released prep plan"));expect(container.textContent).toContain("not confirmed");expect(container.textContent).not.toContain("Sauce:");});
test("changing selected day ignores slower prior response",async()=>{let resolve;api.staffPrepTaskPlan.mockImplementationOnce(()=>new Promise(r=>{resolve=r;}));await renderStaff();const first=api.staffPrepTaskPlan.mock.calls[0][1];await input("Staff prep date",day);await act(async()=>resolve({...staffRead(first.day),tasks:[{...staffRead(first.day).tasks[0],name:"Old plan"}]}));expect(container.textContent).not.toContain("Old plan");expect(container.textContent).toContain("Sauce:");});
test("unreleased staff read shows selected-day absence and holds accidental tasks",async()=>{api.staffPrepTaskPlan.mockImplementation((rid,b)=>Promise.resolve({...staffRead(b.day),status:"draft",tasks:[]}));await renderStaff();expect(container.textContent).toContain("No released plan for this selected date");api.staffPrepTaskPlan.mockImplementation((rid,b)=>Promise.resolve({...staffRead(b.day),status:"draft"}));await click(button("Refresh released prep plan"));expect(container.textContent).toContain("not confirmed");});
test("native portal roster selection never calls legacy PIN elevation or legacy prep sheets",async()=>{const elevate=jest.fn();await act(async()=>root.render(<StaffSheet onElevate={elevate}/>));await click(container.querySelector('[data-testid="staff-store-berts"]'));await change(container.querySelector('[data-testid="staff-pin-entry"]'),"4826");await click(container.querySelector('[data-testid="staff-unlock-button"]'));await click(container.querySelector(`[data-testid="staff-roster-pick-${member.id}"]`));expect(api.identifyStaffMember).not.toHaveBeenCalled();expect(elevate).not.toHaveBeenCalled();await click(container.querySelector('[data-testid="staff-view-prep"]'));expect(api.staffPrepsheet).not.toHaveBeenCalled();expect(api.staffPrepTaskPlan).toHaveBeenCalled();expect(container.querySelector('[aria-label="Released staff prep plan"]')).toBeTruthy();});
