import React, { act } from "react";
import { createRoot } from "react-dom/client";
import { StaffPrepQuantityForm, StaffPrepCountDrafts, PrepCountDecision, StaffPrepCountReview, quantityText } from "./StaffPrepCounts";
import * as api from "../lib/api";
jest.mock("../lib/api",()=>({__esModule:true,staffPrepCountDrafts:jest.fn(),submitStaffPrepCountDraft:jest.fn(),staffPrepCountSetup:jest.fn(),previewStaffPrepCountSheet:jest.fn(),issueStaffPrepCountSheet:jest.fn(),previewStaffPrepCountDecision:jest.fn(),decideStaffPrepCountSheet:jest.fn()}));
const item={product_id:"product-1",product_version_id:"version-1",profile_id:"profile-1",name:"Invented sauce",base_unit:"lb",counted_unit:"bag",factor:"2.123456789012"};
const stamp={performed_at:"2026-10-07T22:00:00-04:00",business_date:"2026-10-07",timezone_name:"America/New_York",calendar_date_confirmed:true,note:"All prep storage"};
const sheet={id:"sheet-1",store_id:"berts",performed_at:"2026-10-08 02:00:00+00:00",business_date:stamp.business_date,timezone_name:stamp.timezone_name,sheet_snapshot:{store_id:"berts",stamp,items:[item]}};
const empty={sheet,reviewHash:"a".repeat(64),latest:null,history:[],errors:[],decision:null};
const initial={id:"submission-1",sheet_id:sheet.id,store_id:"berts",revision:1,counter_name:"Claimed Counter",credential_kind:"shared_pin",quantities:[{product_id:item.product_id,quantity:"0",evidence:"Measured empty"}]};
const review={...empty,latest:initial,history:[initial]};
const observation={reviewHash:"b".repeat(64),review:{purpose:"count",kind:"initial",performed_at:stamp.performed_at,business_date:stamp.business_date,timezone_name:stamp.timezone_name,reason:"Reviewed quantities",lines:[{...item,quantity:"0",evidence:"Measured empty",base_quantity:"0"}]}};
const previewDecision=body=>({current:review,decision:body,observation:body.decision==="accepted"?{...observation,review:{...observation.review,reason:body.note}}:null});
function submitAck(body,key,rev=1){const {pin,...submitted_body}=body;const submission={id:"saved-"+rev,sheet_id:sheet.id,store_id:"berts",revision:rev,request_key:key,counter_name:body.counter_name,credential_kind:"shared_pin",quantities:body.lines,submitted_body};return {submission,current:{...empty,latest:submission,history:[submission]}};}
function decisionAck(body,key){const p=previewDecision({decision:body.decision,note:body.note,reviewed:true});const decision={id:"decision-1",sheet_id:sheet.id,store_id:"berts",submission_id:initial.id,decision:body.decision,note:body.note,request_key:key,observation_id:p.observation?"observation-1":null,review_snapshot:p};return {decision,current:{...review,decision},observation:p.observation?{id:"observation-1",store_id:"berts",review_hash:p.observation.reviewHash,review_snapshot:p.observation.review}:null};}
const setup={store_id:"berts",products:[{product_id:item.product_id,id:item.product_version_id,name:item.name,base_unit:item.base_unit}],profiles:[{id:item.profile_id,product_version_id:item.product_version_id,source_unit:item.counted_unit,base_units_per_source_unit:item.factor}],sheets:[]};
let root,container,uuid;
beforeEach(()=>{global.IS_REACT_ACT_ENVIRONMENT=true;uuid=0;Object.defineProperty(global,"crypto",{configurable:true,value:{randomUUID:()=>`request-${++uuid}`}});root=createRoot(container=document.createElement("div"));document.body.appendChild(container);jest.clearAllMocks();api.staffPrepCountDrafts.mockResolvedValue([empty]);api.staffPrepCountSetup.mockResolvedValue(setup);api.previewStaffPrepCountDecision.mockImplementation((rid,id,body)=>Promise.resolve(previewDecision(body)));api.decideStaffPrepCountSheet.mockImplementation((rid,id,body,key)=>Promise.resolve(decisionAck(body,key)));});
afterEach(async()=>{await act(async()=>root.unmount());container.remove();});
const render=el=>act(async()=>root.render(el));
const button=text=>[...container.querySelectorAll("button")].find(b=>b.textContent===text);
const click=el=>act(async()=>el.click());
async function input(label,value){const el=container.querySelector(`[aria-label="${label}"]`);await act(async()=>{Object.getOwnPropertyDescriptor(el.tagName==="SELECT"?HTMLSelectElement.prototype:HTMLInputElement.prototype,"value").set.call(el,value);el.dispatchEvent(new Event(el.tagName==="SELECT"?"change":"input",{bubbles:true}));});}
async function measurements(quantity="0"){await input("Prep counter name","Claimed Counter");await input("Prep measurement note","Measured full scope");await input("Prep quantity product-1",quantity);await input("Prep evidence product-1","Measured empty");}
async function decision(){await input("Prep count decision note","Reviewed quantities");await click(button("Preview prep count decision"));await click(container.querySelector('[aria-label="Confirm prep count decision"]'));}

test("quantities preserve exact precision and reject negative, scientific, nonfinite and overly precise input",()=>{expect(quantityText("0002.123456789012")).toBe("2.123456789012");expect(quantityText("00.000")).toBe("0");for(const v of ["-1","NaN","1e3","0.1234567890123","99999999999999999"]){expect(()=>quantityText(v)).toThrow();}});
test.each([["",null],["0","0"]])("staff unknown versus measured zero remains explicit (%s)",async(q,expected)=>{const submit=jest.fn().mockImplementation((body,key)=>Promise.resolve(submitAck(body,key)));await render(<StaffPrepQuantityForm rid="berts" review={empty} onSubmit={submit}/>);await measurements(q);await click(button("Submit prep quantities for review"));expect(submit.mock.calls[0][0].lines[0].quantity).toBe(expected);expect(submit.mock.calls[0][0].lines[0]).not.toHaveProperty("inventory_value");expect(container.textContent).toContain("saved and confirmed");expect(container.textContent).toContain("2.123456789012 lb");});
test("interrupted staff save survives navigation, retains exact request and excludes PIN from retained drafts",async()=>{const drafts=new Map(),submit=jest.fn().mockRejectedValueOnce(new Error("Connection interrupted")).mockImplementation((body,key)=>Promise.resolve(submitAck(body,key)));await render(<StaffPrepQuantityForm rid="berts" review={empty} pin="4826" drafts={drafts} onSubmit={submit}/>);await measurements("2.123456789012");await click(button("Submit prep quantities for review"));expect(container.querySelector("fieldset").disabled).toBe(true);expect(JSON.stringify([...drafts])).not.toContain("4826");await render(<div>Other view</div>);await render(<StaffPrepQuantityForm rid="berts" review={empty} pin="4826" drafts={drafts} onSubmit={submit}/>);await click(button("Retry same prep submission"));expect(submit.mock.calls[1]).toEqual(submit.mock.calls[0]);});
test("wrong payload or request acknowledgement holds staff success and exact retry",async()=>{const submit=jest.fn().mockImplementation((body,key)=>Promise.resolve(submitAck({...body,note:"different saved note"},key)));await render(<StaffPrepQuantityForm rid="berts" review={empty} onSubmit={submit}/>);await measurements();await click(button("Submit prep quantities for review"));expect(container.textContent).toContain("was not confirmed");expect(container.querySelector('[role="status"]')).toBeNull();await click(button("Retry same prep submission"));expect(submit.mock.calls[1]).toEqual(submit.mock.calls[0]);});
test("a saved older revision is acknowledged with current revision instead of overwriting later evidence",async()=>{const submit=jest.fn().mockImplementation((body,key)=>{const r=submitAck(body,key),newer={...r.submission,id:"newer",revision:2};return Promise.resolve({...r,current:{...r.current,latest:newer,history:[newer,r.submission]}});});await render(<StaffPrepQuantityForm rid="berts" review={empty} onSubmit={submit}/>);await measurements();await click(button("Submit prep quantities for review"));expect(container.textContent).toContain("revision 1 saved");expect(container.textContent).toContain("Latest recorded revision: 2");});
test("late staff save cannot mutate another location or announce success there",async()=>{let resolve;const drafts=new Map(),submit=jest.fn().mockImplementation(()=>new Promise(r=>{resolve=r;}));await render(<StaffPrepQuantityForm key="berts" rid="berts" review={empty} drafts={drafts} onSubmit={submit}/>);await measurements();await click(button("Submit prep quantities for review"));const other={...empty,sheet:{...sheet,id:"other-sheet",store_id:"rudds",sheet_snapshot:{...sheet.sheet_snapshot,store_id:"rudds"}}};await render(<StaffPrepQuantityForm key="rudds" rid="rudds" review={other} drafts={drafts} onSubmit={submit}/>);await act(async()=>resolve(submitAck(...submit.mock.calls[0])));expect(container.querySelector('[role="status"]')).toBeNull();expect(drafts.get("staff-prep-submit:berts:sheet-1").pending).toBeTruthy();});
test("an absent closed sheet does not hide an uncertain retained request",async()=>{const drafts=new Map();api.submitStaffPrepCountDraft.mockRejectedValue(new Error("Uncertain response"));await render(<StaffPrepCountDrafts rid="berts" pin="4826" drafts={drafts}/>);await measurements();await click(button("Submit prep quantities for review"));api.staffPrepCountDrafts.mockResolvedValue([]);await click(button("Refresh prep count sheets"));expect(button("Retry same prep submission")).toBeTruthy();expect(container.textContent).not.toContain("No open prep count sheets");});
test("failed or wrong-location staff read is not an empty-count success",async()=>{api.staffPrepCountDrafts.mockRejectedValueOnce(new Error("Database unavailable"));await render(<StaffPrepCountDrafts rid="berts"/>);expect(container.textContent).toContain("Database unavailable");expect(container.textContent).not.toContain("No open prep");api.staffPrepCountDrafts.mockResolvedValue([{...empty,sheet:{...sheet,store_id:"rudds"}}]);await click(button("Refresh prep count sheets"));expect(container.textContent).toContain("were not confirmed");expect(container.querySelector('[aria-label="Prep counter name"]')).toBeNull();});
test("manager acceptance requires a preview and explicit confirmation and retains original measurements",async()=>{await render(<PrepCountDecision rid="berts" review={review}/>);expect(button("Save reviewed prep count decision").disabled).toBe(true);expect(container.querySelector('[aria-label="Prep quantity product-1"]')).toBeNull();await decision();await click(button("Save reviewed prep count decision"));expect(api.decideStaffPrepCountSheet.mock.calls[0][2]).toMatchObject({decision:"accepted",expected_review_hash:review.reviewHash,expected_observation_hash:observation.reviewHash,reviewed:true});expect(container.textContent).toContain("decision confirmed: accepted");});
test("changed submitted review invalidates the manager's older preview before save",async()=>{const drafts=new Map();await render(<PrepCountDecision rid="berts" review={review} drafts={drafts}/>);await decision();await render(<PrepCountDecision rid="berts" review={{...review,reviewHash:"c".repeat(64)}} drafts={drafts}/>);await click(button("Save reviewed prep count decision"));expect(api.decideStaffPrepCountSheet).not.toHaveBeenCalled();expect(container.textContent).toContain("latest submission");});
test("manager rejection has no observation or accounting write",async()=>{await render(<PrepCountDecision rid="berts" review={review}/>);await input("Prep count decision","rejected");await decision();await click(button("Save reviewed prep count decision"));expect(api.decideStaffPrepCountSheet.mock.calls[0][2].expected_observation_hash).toBeNull();expect(container.textContent).toContain("confirmed: rejected");});
test("wrong observation acknowledgement cannot clear manager request and retry survives remount",async()=>{const drafts=new Map();api.decideStaffPrepCountSheet.mockImplementationOnce((rid,id,body,key)=>Promise.resolve({...decisionAck(body,key),observation:{id:"unrelated",store_id:"berts"}}));await render(<PrepCountDecision rid="berts" review={review} drafts={drafts}/>);await decision();await click(button("Save reviewed prep count decision"));expect(container.textContent).toContain("was not confirmed");await render(<div>Other view</div>);await render(<PrepCountDecision rid="berts" review={review} drafts={drafts}/>);await click(button("Retry same prep count decision"));expect(api.decideStaffPrepCountSheet.mock.calls[1]).toEqual(api.decideStaffPrepCountSheet.mock.calls[0]);expect(container.textContent).toContain("confirmed: accepted");});
test("manager malformed count preview is held before confirmation",async()=>{api.previewStaffPrepCountDecision.mockImplementation((rid,id,body)=>Promise.resolve({...previewDecision(body),observation:{...observation,review:{...observation.review,lines:[{...observation.review.lines[0],quantity:"999"}]}}}));await render(<PrepCountDecision rid="berts" review={review}/>);await input("Prep count decision note","Reviewed quantities");await click(button("Preview prep count decision"));expect(container.textContent).toContain("was not confirmed");expect(button("Save reviewed prep count decision").disabled).toBe(true);});
test("issue pins explicit units/date and retries its reviewed request after interruption",async()=>{api.previewStaffPrepCountSheet.mockImplementation((rid,body)=>{const {units,...s}=body;return Promise.resolve({reviewHash:"d".repeat(64),review:{store_id:"berts",stamp:s,items:[item]}});});api.issueStaffPrepCountSheet.mockRejectedValueOnce(new Error("Interrupted")).mockImplementation((rid,body,key)=>{const {units,...s}=body.sheet;const issued={...sheet,request_key:key,review_hash:body.expected_review_hash,sheet_snapshot:{store_id:"berts",stamp:s,items:[item]}};return Promise.resolve({sheet:issued,current:{...empty,sheet:issued}});});await render(<StaffPrepCountReview rid="berts" drafts={new Map()}/>);await input("Prep sheet physical time",stamp.performed_at);await input("Prep sheet business date",stamp.business_date);await click(container.querySelector('[aria-label="Prep sheet calendar confirmed"]'));await input("Prep sheet instructions",stamp.note);await input("Prep sheet unit product-1",item.profile_id);await click(button("Preview issued prep sheet"));await click(container.querySelector('[aria-label="Confirm issued prep sheet"]'));await click(button("Issue reviewed prep sheet"));await click(button("Retry same prep sheet issue"));expect(api.issueStaffPrepCountSheet.mock.calls[1]).toEqual(api.issueStaffPrepCountSheet.mock.calls[0]);expect(api.issueStaffPrepCountSheet.mock.calls[0][1].sheet.units).toEqual([{product_version_id:item.product_version_id,profile_id:item.profile_id}]);expect(container.textContent).toContain("Review prep count");});
test("rejected manager request retains draft until an explicit fresh review is chosen",async()=>{api.decideStaffPrepCountSheet.mockRejectedValue({response:{status:409,data:{detail:"Submission changed"}}});await render(<PrepCountDecision rid="berts" review={review} drafts={new Map()}/>);await decision();await click(button("Save reviewed prep count decision"));expect(button("Retry same prep count decision")).toBeTruthy();await click(button("Review a revised prep count decision"));expect(container.querySelector('[aria-label="Prep count decision note"]').value).toBe("Reviewed quantities");expect(button("Save reviewed prep count decision").disabled).toBe(true);});
test("clearing the portal draft scope prevents an old response from restoring cleared state",async()=>{const drafts=new Map();let resolve;const submit=jest.fn().mockImplementation(()=>new Promise(r=>{resolve=r;}));await render(<StaffPrepQuantityForm rid="berts" review={empty} drafts={drafts} onSubmit={submit}/>);await measurements();await click(button("Submit prep quantities for review"));drafts.clear();await act(async()=>resolve(submitAck(...submit.mock.calls[0])));expect(drafts.size).toBe(0);expect(container.querySelector('[role="status"]')).toBeNull();});
test("an older pending refresh cannot remove a newly acknowledged staff submission",async()=>{const drafts=new Map();let refresh;api.submitStaffPrepCountDraft.mockImplementation((rid,id,body,key)=>Promise.resolve(submitAck(body,key)));await render(<StaffPrepCountDrafts rid="berts" drafts={drafts}/>);await measurements();api.staffPrepCountDrafts.mockImplementationOnce(()=>new Promise(r=>{refresh=r;}));await click(button("Refresh prep count sheets"));await click(button("Submit prep quantities for review"));await act(async()=>refresh([]));expect(container.textContent).toContain("saved and confirmed");expect(container.textContent).not.toContain("No open prep count sheets");expect(container.querySelector('[aria-label="Prep quantity product-1"]')).toBeTruthy();});
