"""Transform the MongoDB prep_stock/prep_logs export into SQL for the new Supabase
schema. Reads the JSON backup, writes a .sql file -- doesn't connect to Postgres
directly, applied via the Supabase MCP tools. See docs/SUPABASE_MIGRATION_PLAN.md
(step 3).

Run: python scripts/migrate_prep_stock_and_logs.py <backup_dir> [out.sql]

Both prep_stock and prep_logs reference a recipe by Mongo id (e.g. "prep_71fe6a48"),
resolved by (store_id, name) lookup against the already-migrated dishes -- same
pattern as migrate_dishes.py's prep-to-prep references.
"""
import json
import sys
from pathlib import Path

STORE_ID_MAP = {"berts": "berts", "rudds": "rudds", "papa_leonis": "papa"}


def sql_str(v):
    if v is None or v == "":
        return "NULL"
    return "'" + str(v).replace("'", "''") + "'"

def sql_num(v):
    return "NULL" if v is None else str(v)

def sql_jsonb(v):
    return "'" + json.dumps(v or []).replace("'", "''") + "'::jsonb"


def build_prep_stock_sql(prep_stock):
    rows = []
    for ps in prep_stock:
        rid = ps["restaurantId"]
        store_id = STORE_ID_MAP.get(rid)
        if not store_id:
            print(f"  SKIP prep_stock (unknown store '{rid}'): {ps.get('name')}")
            continue
        rows.append(f"""INSERT INTO prep_recipe_stock (dish_id, store_id, on_hand, containers)
SELECT dish.id, {sql_str(store_id)}, {sql_num(ps.get('onHand'))}, {sql_jsonb(ps.get('containers'))}
FROM dishes dish WHERE dish.store_id = {sql_str(store_id)} AND dish.name = {sql_str(ps['name'])};""")
    return rows


def main():
    backup_dir = Path(sys.argv[1]) if len(sys.argv) > 1 else None
    if not backup_dir or not backup_dir.exists():
        print("Usage: python scripts/migrate_prep_stock_and_logs.py <backup_dir> [out.sql]")
        sys.exit(1)
    out_path = Path(sys.argv[2]) if len(sys.argv) > 2 else backup_dir / "migrate_prep_stock_and_logs.sql"

    prep_stock = json.loads((backup_dir / "prep_stock.json").read_text())
    prep_logs = json.loads((backup_dir / "prep_logs.json").read_text())
    dishes = json.loads((backup_dir / "dishes.json").read_text())
    print(f"Loaded {len(prep_stock)} prep_stock, {len(prep_logs)} prep_logs, {len(dishes)} dishes from {backup_dir}")

    # mongo dish id -> (store_id, name), for resolving prep_logs.recipeId
    mongo_id_to_key = {}
    for d in dishes:
        store_id = STORE_ID_MAP.get(d["restaurantId"])
        if store_id:
            mongo_id_to_key[d["id"]] = (store_id, d["name"])

    stock_rows = build_prep_stock_sql(prep_stock)

    log_rows = []
    skipped = 0
    for log in prep_logs:
        rid = log["restaurantId"]
        store_id = STORE_ID_MAP.get(rid)
        if not store_id:
            print(f"  SKIP prep_log (unknown store '{rid}'): {log.get('name')}")
            skipped += 1
            continue
        recipe_key = mongo_id_to_key.get(log.get("recipeId")) if log.get("recipeId") else None
        if recipe_key:
            target_store, target_name = recipe_key
            recipe_select = f"(SELECT dish.id FROM dishes dish WHERE dish.store_id = {sql_str(target_store)} AND dish.name = {sql_str(target_name)})"
        else:
            recipe_select = "NULL"
        log_rows.append(
            f"({sql_str(store_id)}, {sql_str(log['kind'])}, {recipe_select}, {sql_str(log.get('name'))}, "
            f"{sql_num(log.get('batches'))}, {sql_num(log.get('produced'))}, {sql_str(log.get('yieldUOM'))}, "
            f"{sql_jsonb(log.get('usage'))}, {sql_jsonb(log.get('containers'))}, {sql_num(log.get('totalCost'))}, "
            f"{sql_str(log.get('date'))}, {sql_str(log.get('createdAt'))})"
        )

    sql = ["-- Generated by scripts/migrate_prep_stock_and_logs.py -- review before applying.\n"]
    sql.append("\n".join(stock_rows) + "\n")
    sql.append(
        "INSERT INTO prep_logs (store_id, kind, dish_id, name, batches, produced, yield_uom, usage, containers, total_cost, date, created_at) VALUES\n"
        + ",\n".join(log_rows) + ";\n"
    )

    out_path.write_text("\n".join(sql), encoding="utf-8")
    print(f"Wrote {len(stock_rows)} prep_recipe_stock, {len(log_rows)} prep_logs ({skipped} skipped) -> {out_path}")


if __name__ == "__main__":
    main()
