"""Transform the MongoDB dishes export (menu items + prep recipes) into SQL for the
new Supabase schema. Reads the JSON backup, writes a .sql file -- doesn't connect to
Postgres directly, applied via the Supabase MCP tools. See
docs/SUPABASE_MIGRATION_PLAN.md (step 3).

Run: python scripts/migrate_dishes.py <backup_dir> [out.sql]

Same item-code remap as migrate_items_and_invoices.py: {mongoRestaurantId}_{controlNumber}.
dish_lines that reference another recipe (sourceType: "prep") are resolved by looking
the target dish up by (store_id, name) after insertion, not by a fabricated id --
dish names are unique within each restaurant in the current data.
"""
import json
import sys
from pathlib import Path

STORE_ID_MAP = {"berts": "berts", "rudds": "rudds", "papa_leonis": "papa"}


def sql_str(v):
    if v is None or v == "":
        return "NULL"
    return "'" + str(v).replace("'", "''") + "'"

def sql_num(v):
    return "NULL" if v is None else str(v)

def item_code(rid, control_number):
    return f"{rid}_{control_number}"


def build_dishes_sql(dishes):
    dish_rows = []
    # mongo dish id -> (store_id, name), used to resolve sourceType="prep" lines
    mongo_id_to_key = {}
    for d in dishes:
        rid = d["restaurantId"]
        store_id = STORE_ID_MAP.get(rid)
        if not store_id:
            print(f"  SKIP dish (unknown store '{rid}'): {d.get('name')}")
            continue
        mongo_id_to_key[d["id"]] = (store_id, d["name"])
        recipe_type = d.get("recipeType", "menu")
        dish_rows.append(
            f"({sql_str(store_id)}, {sql_str(d['name'])}, {sql_str(d.get('menuCode'))}, {sql_str(recipe_type)}, "
            f"{sql_num(d.get('price'))}, {sql_num(d.get('targetPct'))}, {sql_num(d.get('yieldQty'))}, "
            f"{sql_str(d.get('yieldUOM'))}, {sql_num(d.get('prepPar'))}, {sql_str(d.get('procedure'))}, "
            f"{sql_str(d.get('equipment'))}, {sql_str(d.get('shelfLife'))}, {sql_str(d.get('menuCategory'))}, "
            f"{sql_str(d.get('description'))}, {sql_str(d.get('photoUrl'))}, {sql_str(d.get('portionNote'))}, "
            f"{sql_str(d.get('frequency'))})"
        )
    return dish_rows, mongo_id_to_key


def build_dish_lines_sql(dishes, mongo_id_to_key):
    line_selects = []
    skipped = 0
    for d in dishes:
        rid = d["restaurantId"]
        store_id = STORE_ID_MAP.get(rid)
        if not store_id:
            continue
        dish_name = d["name"]
        for l in d.get("lines", []):
            qty = l.get("qty")
            if l.get("sourceType") == "item":
                code = item_code(rid, l["controlNumber"])
                line_selects.append(f"""INSERT INTO dish_lines (dish_id, source_type, item_code, qty)
SELECT dish.id, 'item', {sql_str(code)}, {sql_num(qty)}
FROM dishes dish WHERE dish.store_id = {sql_str(store_id)} AND dish.name = {sql_str(dish_name)};""")
            elif l.get("sourceType") == "prep":
                target = mongo_id_to_key.get(l.get("recipeId"))
                if not target:
                    print(f"  SKIP dish_line (unresolved recipeId '{l.get('recipeId')}') on {store_id}/{dish_name}")
                    skipped += 1
                    continue
                target_store, target_name = target
                line_selects.append(f"""INSERT INTO dish_lines (dish_id, source_type, prep_dish_id, qty)
SELECT dish.id, 'prep', prep.id, {sql_num(qty)}
FROM dishes dish, dishes prep
WHERE dish.store_id = {sql_str(store_id)} AND dish.name = {sql_str(dish_name)}
  AND prep.store_id = {sql_str(target_store)} AND prep.name = {sql_str(target_name)};""")
    return line_selects, skipped


def main():
    backup_dir = Path(sys.argv[1]) if len(sys.argv) > 1 else None
    if not backup_dir or not backup_dir.exists():
        print("Usage: python scripts/migrate_dishes.py <backup_dir> [out.sql]")
        sys.exit(1)
    out_path = Path(sys.argv[2]) if len(sys.argv) > 2 else backup_dir / "migrate_dishes.sql"

    dishes = json.loads((backup_dir / "dishes.json").read_text())
    print(f"Loaded {len(dishes)} dishes from {backup_dir}")

    dish_rows, mongo_id_to_key = build_dishes_sql(dishes)
    line_selects, skipped = build_dish_lines_sql(dishes, mongo_id_to_key)

    sql = ["-- Generated by scripts/migrate_dishes.py -- review before applying.\n"]
    sql.append(
        "INSERT INTO dishes (store_id, name, menu_code, recipe_type, price, target_pct, yield_qty, yield_uom, "
        "prep_par, procedure, equipment, shelf_life, menu_category, description, photo_url, portion_note, frequency) VALUES\n"
        + ",\n".join(dish_rows) + ";\n"
    )
    sql.append("\n".join(line_selects))

    out_path.write_text("\n".join(sql), encoding="utf-8")
    print(f"Wrote {len(dish_rows)} dishes, {len(line_selects)} dish_lines ({skipped} skipped) -> {out_path}")


if __name__ == "__main__":
    main()
